name = "emaildiscovery"
account_id = "95f1a82ff6a6e32e66b28a134e1e0287"
compatibility_date = "2024-05-01"

main = "src/index.js"
workers_dev = true

[site]
bucket = "./public"

[[bindings]]
type = "static_content"
name = "STATIC"
directory = "./public"
